language: python

matrix:
  include:
    - name: Python 2.7
      python: 2.7
    - name: Python 3.7
      python: 3.7
      dist: xenial

env:
  - SPARK=2.4 SPARK_URL="http://apache.cs.utah.edu/spark/spark-2.4.2/spark-2.4.2-bin-hadoop2.7.tgz"

before_install:
  - mkdir -p /opt
  - wget -q -O /opt/spark.tgz "$SPARK_URL"
  - tar xzf /opt/spark.tgz -C /opt/
  - rm /opt/spark.tgz
  - ln -s $(find /opt -maxdepth 1 -name "spark-*" -print0) /opt/spark

script: pytest
