dist: trusty
language: python

matrix:
  include:
    - name: Python 2.7
      python: 2.7
    - name: Python 3.6
      python: 3.6

env:
  - SPARK=2.4 SPARK_URL="http://apache.cs.utah.edu/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz"

before_install:
  - mkdir -p /opt
  - wget -nv -O /opt/spark.tgz "$SPARK_URL"
  - tar xzf /opt/spark.tgz -C /opt/
  - rm /opt/spark.tgz
  - ln -s $(find /opt -maxdepth 1 -name "spark-*" -print0) /opt/spark
  - pip install --upgrade pytest

install:
  - python setup.py install

script: pytest
