language: python

matrix:
  include:
    - name: Python 2.7
      python: 2.7
    - name: Python 3.7
      python: 3.7
      dist: xenial

addons:
  apt:
    packages:
      - oracle-java9-set-default

env:
  - SPARK=2.4 SPARK_URL="http://apache.cs.utah.edu/spark/spark-2.4.2/spark-2.4.2-bin-hadoop2.7.tgz"

before_install:
  - mkdir -p /opt
  - cd /opt
  - wget -q -O spark.tgz "$SPARK_URL"
  - tar xzf spark.tgz
  - rm spark.tgz
  - ln -s $(find . -maxdepth 1 -name "spark-*" -print0) ./spark

install:
  - python setup.py install

script: pytest
